spring.application.name=my-api
server.port=${PORT:8080}
spring.data.mongodb.uri=mongodb+srv://mohamedislamr15_db_user:db2003@cluster0.rerztzy.mongodb.net/my_api_db?retryWrites=true&w=majority&appName=Cluster0
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG