spring.application.name=my-api
server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI}
server.error.include-message=always
server.error.include-stacktrace=always
logging.level.org.springframework.web=DEBUG